# Generated by Django 4.1.4 on 2022-12-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('annonceId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('userId', models.IntegerField()),
                ('bienId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BienImmobilier',
            fields=[
                ('bienImmobilerId', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('surface', models.IntegerField()),
                ('prix', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=45)),
                ('prenom', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=10)),
                ('adresse', models.CharField(max_length=50)),
            ],
        ),
    ]
