# Generated by Django 4.1.4 on 2022-12-27 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bienimmobilier',
            old_name='bienImmobilerId',
            new_name='bienImmobilierId',
        ),
    ]
