# Generated by Django 4.1.4 on 2022-12-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_bienimmobilerid_bienimmobilier_bienimmobilierid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='')),
                ('bienid', models.IntegerField()),
            ],
        ),
    ]
