# Generated by Django 4.1.4 on 2022-12-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienimmobilier',
            name='adresse',
            field=models.CharField(default='a', max_length=80),
        ),
        migrations.AddField(
            model_name='bienimmobilier',
            name='commune',
            field=models.CharField(default='c', max_length=45),
        ),
        migrations.AddField(
            model_name='bienimmobilier',
            name='wilaya',
            field=models.CharField(default='w', max_length=45),
        ),
    ]
