# Generated by Django 4.1.4 on 2023-01-01 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_annonce_bienid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='bienId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.bienimmobilier'),
        ),
    ]
