# Generated by Django 4.1.4 on 2023-01-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_user_adresse_alter_user_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adresse',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
