# Generated by Django 4.1.4 on 2023-01-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_user_adresse_alter_user_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienimmobilier',
            name='latitude',
            field=models.FloatField(default=36.7),
        ),
        migrations.AddField(
            model_name='bienimmobilier',
            name='longitude',
            field=models.FloatField(default=2.985),
        ),
    ]
