# Generated by Django 4.1.4 on 2023-01-19 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_bienimmobilier_latitude_bienimmobilier_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('msgId', models.AutoField(primary_key=True, serialize=False)),
                ('emiteurId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
    ]
