# Generated by Django 4.1.4 on 2023-01-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recepteurId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='emiteurId',
            field=models.IntegerField(default=0),
        ),
    ]
