# Generated by Django 4.1.4 on 2023-01-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_message_recepteurid_alter_message_emiteurid'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='contenu',
            field=models.CharField(default='msg', max_length=150),
        ),
    ]
