# Generated by Django 4.1.4 on 2023-02-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_message_contenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='Categorie',
            field=models.CharField(choices=[('vente', 'Vente'), ('location', 'Location'), ('echange', 'Echange'), ('location pour vacance', 'Locationpourvacance')], default='vente', max_length=25),
        ),
    ]
